apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod  # Name of the pod
  labels:
    app: nginx     # Label for identifying the pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
        requests:
          cpu: "0.5"
          memory: "256Mi"  # Port to expose within the container
