apiVersion: v1
kind: Service
metadata:
  name: nginx-service  # Name of the Service
spec:
  selector:
    app: nginx  # Label selector to match pods
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the Service
      targetPort: 80  # Port on pods to forward traffic to
  type: ClusterIP  # Type of Service (ClusterIP, NodePort, LoadBalancer, etc.)
