kubernetes_learning_curve:
  deployments:
    description: "High-level abstraction for managing ReplicaSets and Pods, supporting updates and rollbacks."
    structure:
      apiVersion: "apps/v1"
      kind: "Deployment"
      metadata:
        name: "deployment-sample"
        labels:
          tier: "backend"
      spec:
        replicas: 3
        strategy:
          type: "Recreate"
        template:
          metadata:
            labels:
              app: "nginx"
          spec:
            containers:
              - name: "nginx-container"
                image: "nginx"
        selector:
          matchLabels:
            app: "nginx"
    commands:
      management:
        - "kubectl create -f deployment.yaml"
        - "kubectl apply -f deployment.yaml --record"
        - "kubectl get deployments"
        - "kubectl edit deployment deployment-name --record"
        - "kubectl delete deployment deployment-name"
      rollout:
        - "kubectl rollout status deployment deployment-name"
        - "kubectl rollout history deployment deployment-name"
        - "kubectl rollout undo deployment deployment-name"
      Imperative-command: 
        - "kubectl run --image=image-name pod-name"
        - "kubectl create deployment --image=image-name deployment-name"
        - "kubectl scale deployment deployment-name --replicas=4"
        - "kubectl edit deployment deployment-name"
        - "kubeclt expose deployment deployment-name --port 80"
        - "kubectl set image deployment deployment-name image-name=image-repo:tag"

      Declarative-Command:
        - "kubectl apply -f deployment.yaml {both for create and update}"