version: "3"

services:
  music:
    build:
      context: ./music
    deploy:
      replicas: 1
    ports:
      - 3000:3000

  user:
    build:
      context: ./users
    deploy:
      replicas: 1
    ports:
      - 3001:3000

  playlist:
    build:
      context: ./playlists
    deploy:
      replicas: 1
    ports:
      - 3002:3000
